import Banner from '@/components/Banner';
import Row from '@/components/Row';
import requests from '@/utils/requests';
import Head from 'next/head';
import Image from 'next/image';
export default function Home({ popularMovies }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header en _app.js */}
      <Banner popularMovies={popularMovies.slice(0,6)} />
      <Row popularMovies={popularMovies.slice(0,7)}  titulo ={'Solo para ti'} slides={6}/>
      {/* Solo para tí */}
      {/* Mi lista */}
      {/* Explora por género */}
      {/* En tendencia */}
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(requests.fetchPopular);
  const data = await res.json();
  const popular = data.results;

  return {
    props: {
      popularMovies: popular,
    },
  };
}
